"""mitiphy demo --dry-run end-to-end smoke test on bundled fixtures.

Builds a Target manually, feeds synthetic observations into the enricher +
scorer + reporter, writes a CASE-demo-* folder. No network calls.
"""

from __future__ import annotations

import secrets
import time

from .. import __version__
from ..audit.chain import AuditChain
from ..core.config import get_settings
from ..core.observation import Confidence, Observation, Severity
from ..core.target import Target
from ..enrich.attck import ATTCKEnricher
from ..report.renderer import Case, Reporter
from ..score.scorer import RiskScorer


def run_demo(dry_run: bool = True) -> dict[str, str]:
    s = get_settings()
    s.ensure_dirs()
    chain = AuditChain(s.audit_db)
    chain.ensure_genesis(installer_version=__version__)

    target = Target.from_string("evil-demo.example.com")
    target.metadata["seed_cves"] = "CVE-2024-3094 CVE-2021-44228"

    observations: list[Observation] = [
        Observation(
            kind="subdomain", value="login.evil-demo.example.com",
            source="crt", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="subdomain", value="api.evil-demo.example.com",
            source="crt", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="dns_a", value="203.0.113.42",
            source="dns", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="dns_mx", value="mx1.evil-demo.example.com",
            source="dns", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="nameserver", value="ns1.evil-demo.example.com",
            source="rdap", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="kev_match", value="CVE-2024-3094",
            source="kev", severity=Severity.CRITICAL, confidence=Confidence.HIGH,
            payload={"vendor": "xz-utils", "product": "liblzma"},
        ),
        Observation(
            kind="epss_score", value="CVE-2021-44228",
            source="epss", severity=Severity.HIGH, confidence=Confidence.HIGH,
            payload={"epss": 0.97, "percentile": 0.9999},
        ),
        Observation(
            kind="archive_snapshot", value="http://web.archive.org/web/2023/example",
            source="wayback", severity=Severity.INFO, confidence=Confidence.HIGH,
        ),
        Observation(
            kind="breach", value="example-breach-2023",
            source="hibp", severity=Severity.HIGH, confidence=Confidence.MEDIUM,
            timestamp=time.time() - 30 * 86400,
        ),
    ]

    enricher = ATTCKEnricher()
    techniques = enricher.enrich(observations)
    scorer = RiskScorer()
    score = scorer.score(observations)

    case_id = f"CASE-demo-{int(time.time())}-{secrets.token_hex(2)}"
    case_dir = s.cases_dir / case_id
    case = Case(
        case_id=case_id,
        target=target,
        observations=[o.to_dict() for o in observations],
        techniques=techniques,
        score=score,
        notes="Synthetic demo case — generated by `mitiphy demo`.",
    )
    reporter = Reporter(case_dir)
    written = reporter.write_all(case)
    try:
        written["misp"] = reporter.write_misp(case)
        written["stix"] = reporter.write_stix(case)
    except Exception:
        pass

    chain.append("demo_run", {"case_id": case_id, "dry_run": dry_run, "score": score.score})
    return {k: str(v) for k, v in written.items()}
